# Generated by Django 6.0.5 on 2026-06-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_promotion_review_transaction_vendorsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
