# Generated by Django 6.0.5 on 2026-06-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_hotel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='stars',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
