# Generated by Django 6.0.5 on 2026-06-24 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_hotel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_id', models.CharField(max_length=50, unique=True)),
                ('session_id', models.CharField(max_length=255)),
                ('check_in', models.CharField(max_length=10)),
                ('check_out', models.CharField(max_length=10)),
                ('rooms', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='app.hotel')),
            ],
        ),
    ]
