# Generated by Django 6.0.5 on 2026-06-24 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_roomhold'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='app.roomtype'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_type_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
