# Generated by Django 6.0.5 on 2026-06-24 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_booking_room_type_booking_room_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_type_name',
        ),
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.PositiveIntegerField(default=0)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='app.booking')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.roomtype')),
            ],
        ),
    ]
