# Generated by Django 6.0.5 on 2026-06-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancellation_fee',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_deposit_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_group_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cancellation_free_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='deposit_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
