# Generated by Django 6.0.5 on 2026-06-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_booking_cancellation_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_refundable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cancellation_policy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_refundable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show'), ('relocated', 'Relocated')], default='pending', max_length=20),
        ),
    ]
