# Generated by Django 6.0.5 on 2026-06-29 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_booking_is_refundable_hotel_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RenameField(
            model_name='roomtype',
            old_name='available_rooms',
            new_name='total_rooms',
        ),
        migrations.AddField(
            model_name='roomhold',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='app.roomtype'),
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_name', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='app.booking')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.PositiveIntegerField()),
                ('available_rooms', models.PositiveIntegerField()),
                ('version', models.IntegerField(default=0)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='app.roomtype')),
            ],
            options={
                'unique_together': {('room_type', 'date')},
            },
        ),
    ]
